### ISSUE TITLE
CC2540 - programming

### ISSUE THREAD

**Issue by WebScript** [Ladvien/HM-10#2]
Hello.
I want to connect HM-10 directly to some kind of motion sensor or simply turn 1 led on or off. Do I need CC Debugger for that? Is it okay to buy noname cheap alternatives from eBay? I have already USB FTDI.
Thanks.
P.S. Sorry for stupid questions, I am new to this.

**Comment by Ladvien** [comment]
Morning! :)

You should be able to do this with any 3.3v motion sensor.  You’d use the command AT+PIOX?  (X = pin number).  Also, be aware all the PIO pins can only sink a maximum of 4mA.

To turn an LED on or off, you’ll need a transistor, since again the pins can only source or sink 4mA and most LEDs require power than that.  If you try to power an LED directly from a pin, it’ll probably kill that pin.  So, be careful.

If you have anymore questions, if you wouldn’t mind posting them in the comments here.

http://letsmakerobots.com/content/bluetooth-40-arduino

I’ll be more than happy to try and help.  Good luck!

—Thomas
aka, Ladvien

**Comment by munum** [comment]
I'm doing something similar, but to connect to a piezo buzzer. Is the canonical approach to use the CC Debugger for programming?
